package agent

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/aldous/jevium/internal/page"
)

// Expectation is supplied by the operator, never generated by a model.
// All expectations must match the same fresh observation.
type Expectation struct {
	Field string `json:"field"`
	Label string `json:"label,omitempty"`
	Value string `json:"value"`
}

func ParseExpectations(values []string) ([]Expectation, error) {
	out := make([]Expectation, 0, len(values))
	for _, raw := range values {
		var e Expectation
		d := json.NewDecoder(strings.NewReader(raw))
		d.DisallowUnknownFields()
		if err := d.Decode(&e); err != nil {
			return nil, fmt.Errorf("invalid expectation: %w", err)
		}
		if err := d.Decode(new(any)); err != io.EOF {
			return nil, fmt.Errorf("expectation must contain one JSON object")
		}
		switch e.Field {
		case "text", "title", "url":
			if e.Label != "" {
				return nil, fmt.Errorf("%s expectation cannot specify label", e.Field)
			}
		case "value", "checked", "expanded", "selected":
			if e.Label == "" {
				return nil, fmt.Errorf("%s expectation requires exact control label", e.Field)
			}
			if (e.Field == "checked" || e.Field == "expanded" || e.Field == "selected") && e.Value != "true" && e.Value != "false" {
				return nil, fmt.Errorf("%s expectation requires true or false", e.Field)
			}
		default:
			return nil, fmt.Errorf("unsupported expectation field %q", e.Field)
		}
		if e.Value == "" && e.Field != "value" {
			return nil, fmt.Errorf("%s expectation requires a value", e.Field)
		}
		out = append(out, e)
	}
	return out, nil
}

func ExpectationsMatch(expectations []Expectation, p page.Page) bool {
	if len(expectations) == 0 {
		return false
	}
	for _, e := range expectations {
		matched := false
		switch e.Field {
		case "text":
			matched = strings.Contains(p.Text, e.Value)
		case "title":
			matched = p.Title == e.Value
		case "url":
			matched = p.URL == e.Value
		default:
			// An ambiguous label cannot establish the requested outcome.
			nodes := map[string]page.Control{}
			for _, a := range p.Controls {
				if a.Label == e.Label {
					nodes[fmt.Sprint(a.Node)] = a
				}
			}
			if len(nodes) != 1 {
				return false
			}
			for _, a := range nodes {
				switch e.Field {
				case "value":
					matched = a.Value != nil && *a.Value == e.Value
				case "checked":
					matched = a.Checked == e.Value
				case "expanded":
					matched = a.Expanded == e.Value
				case "selected":
					switch v := a.Selected.(type) {
					case bool:
						matched = fmt.Sprint(v) == e.Value
					case string:
						matched = (v == "true" || v == "false") && v == e.Value
					}
				}
			}
		}
		if !matched {
			return false
		}
	}
	return true
}
